import React from "react";
import { BigPictureGallery } from "react-bigpicture";
import "./style.css";




function PortfolioImages() {

    return (
        <div className="borderPortfolio">
            <h1 className="Gallery">Portfolio Gallery</h1>
            <div className="portfolioImagesback">
                <BigPictureGallery loop>
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/wMvhwtO.jpg"
                        src="https://i.imgur.com/wMvhwtO.jpg"
                        caption="Heyyyy"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/A2bZjAD.jpg"
                        src="https://i.imgur.com/A2bZjAD.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc=""
                        src="https://i.imgur.com/CJvfXuT.jpg"
                        alt="https://i.imgur.com/CJvfXuT.jpg"
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/dVHYFfJ.jpg"
                        src="https://i.imgur.com/dVHYFfJ.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/StwBskN.jpg"
                        src="https://i.imgur.com/StwBskN.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/fDsbcx7.jpg"
                        src="https://i.imgur.com/fDsbcx7.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/UI1CR61.jpg"
                        src="https://i.imgur.com/UI1CR61.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/SBccE3e.jpg"
                        src="https://i.imgur.com/SBccE3e.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/eChQRcx.jpg"
                        src="https://i.imgur.com/eChQRcx.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/QzSiKE4.jpg"
                        src="https://i.imgur.com/QzSiKE4.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/yI9sVfO.jpg"
                        src="https://i.imgur.com/yI9sVfO.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/38670Jn.jpg"
                        src="https://i.imgur.com/38670Jn.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/PV9BFbl.jpg"
                        src="https://i.imgur.com/PV9BFbl.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/KtxmNOe.jpg"
                        src="https://i.imgur.com/KtxmNOe.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/zNp7p48.jpg"
                        src="https://i.imgur.com/zNp7p48.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/UmzUJG9.jpg"
                        src="https://i.imgur.com/UmzUJG9.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/7hHlUzP.jpg"
                        src="https://i.imgur.com/7hHlUzP.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/T4knrDB.jpg"
                        src="https://i.imgur.com/T4knrDB.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/nAwELgm.jpg"
                        src="https://i.imgur.com/nAwELgm.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/lG1LpZQ.jpg"
                        src="https://i.imgur.com/lG1LpZQ.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/YKim6TW.jpg"
                        src="https://i.imgur.com/YKim6TW.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/YzMMCtc.jpg"
                        src="https://i.imgur.com/YzMMCtc.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/ixSuHvg.jpg"
                        src="https://i.imgur.com/ixSuHvg.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/KbXBcvo.jpg"
                        src="https://i.imgur.com/KbXBcvo.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/ndw6wJx.jpg"
                        src="https://i.imgur.com/ndw6wJx.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/QN4x7HU.jpg"
                        src="https://i.imgur.com/QN4x7HU.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/25AryIH.jpg"
                        src="https://i.imgur.com/25AryIH.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/ELfQtt7.jpg"
                        src="https://i.imgur.com/ELfQtt7.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/OoOS6xn.jpg"
                        src="https://i.imgur.com/OoOS6xn.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/ccC7Xo5.jpg"
                        src="https://i.imgur.com/ccC7Xo5.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/B5xLCSE.jpg"
                        src="https://i.imgur.com/B5xLCSE.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/gbI6rGT.jpg"
                        src="https://i.imgur.com/gbI6rGT.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/fVGH6U5.jpg"
                        src="https://i.imgur.com/fVGH6U5.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/5knSzcx.jpg"
                        src="https://i.imgur.com/5knSzcx.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/RMq0vRA.jpg"
                        src="https://i.imgur.com/RMq0vRA.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/MJFfUYs.jpg"
                        src="https://i.imgur.com/MJFfUYs.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/aw8ZYIs.jpg"
                        src="https://i.imgur.com/aw8ZYIs.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/lpEYcQt.jpg"
                        src="https://i.imgur.com/lpEYcQt.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/n1Dib0Z.jpg"
                        src="https://i.imgur.com/n1Dib0Z.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/Zz79AKp.jpg"
                        src="https://i.imgur.com/Zz79AKp.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/6nRVINz.jpg"
                        src="https://i.imgur.com/6nRVINz.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/nvZZa21.jpg"
                        src="https://i.imgur.com/nvZZa21.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/Bc6oCIb.jpg"
                        src="https://i.imgur.com/Bc6oCIb.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/8tu9X53.jpg"
                        src="https://i.imgur.com/8tu9X53.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/3dG26vf.jpg"
                        src="https://i.imgur.com/3dG26vf.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/YIa2wwP.jpg"
                        src="https://i.imgur.com/YIa2wwP.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/qrswI4J.jpg"
                        src="https://i.imgur.com/qrswI4J.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/wBozIOo.jpg"
                        src="https://i.imgur.com/wBozIOo.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/THyyUpU.jpg"
                        src="https://i.imgur.com/THyyUpU.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/PTtBTbL.jpg"
                        src="https://i.imgur.com/PTtBTbL.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/LN7QTYB.jpg"
                        src="https://i.imgur.com/LN7QTYB.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/Ua2j3Hn.jpg"
                        src="https://i.imgur.com/Ua2j3Hn.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/U1Mp4rK.jpg"
                        src="https://i.imgur.com/U1Mp4rK.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/qp4SlrG.jpg"
                        src="https://i.imgur.com/qp4SlrG.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/OcIkk7U.jpg"
                        src="https://i.imgur.com/OcIkk7U.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/bT4AaVs.jpg"
                        src="https://i.imgur.com/bT4AaVs.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/n5LPf9L.jpg"
                        src="https://i.imgur.com/n5LPf9L.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/hdwBo7l.jpg"
                        src="https://i.imgur.com/hdwBo7l.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/lCa6vq3.jpg"
                        src="https://i.imgur.com/lCa6vq3.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/rwOfVzo.jpg"
                        src="https://i.imgur.com/rwOfVzo.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/HYusjHc.jpg"
                        src="https://i.imgur.com/HYusjHc.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/MBFAWS0.jpg"
                        src="https://i.imgur.com/MBFAWS0.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/i7BUWTy.jpg"
                        src="https://i.imgur.com/i7BUWTy.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/qxOHZDS.jpg"
                        src="https://i.imgur.com/qxOHZDS.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/xevfgiu.jpg"
                        src="https://i.imgur.com/xevfgiu.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/zxXbDpi.jpg"
                        src="https://i.imgur.com/zxXbDpi.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/5CTUtpv.jpg"
                        src="https://i.imgur.com/5CTUtpv.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/vDSvcz1.jpg"
                        src="https://i.imgur.com/vDSvcz1.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/CDZhQU2.jpg"
                        src="https://i.imgur.com/CDZhQU2.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/TQ4CNu2.jpg"
                        src="https://i.imgur.com/TQ4CNu2.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/3CjCK8b.jpg"
                        src="https://i.imgur.com/3CjCK8b.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/ubneQSP.jpg"
                        src="https://i.imgur.com/ubneQSP.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/3UXLzgn.jpg"
                        src="https://i.imgur.com/3UXLzgn.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/7glEenb.jpg"
                        src="https://i.imgur.com/7glEenb.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/sPCOXBJ.jpg"
                        src="https://i.imgur.com/sPCOXBJ.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/JdCGIZZ.jpg"
                        src="https://i.imgur.com/JdCGIZZ.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/Bb8lPu0.jpg"
                        src="https://i.imgur.com/Bb8lPu0.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/RHQbaVF.jpg"
                        src="https://i.imgur.com/RHQbaVF.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/McA9DcB.jpg"
                        src="https://i.imgur.com/McA9DcB.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/tLkyXCN.jpg"
                        src="https://i.imgur.com/tLkyXCN.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/XxNbaRs.jpg"
                        src="https://i.imgur.com/XxNbaRs.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/fHJCxY9.jpg"
                        src="https://i.imgur.com/fHJCxY9.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/NnFxqrt.jpg"
                        src="https://i.imgur.com/NnFxqrt.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/lkMAGsk.jpg"
                        src="https://i.imgur.com/lkMAGsk.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/hjUs2eM.jpg"
                        src="https://i.imgur.com/hjUs2eM.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/p8aJ9YE.jpg"
                        src="https://i.imgur.com/p8aJ9YE.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/OtutZTx.jpg"
                        src="https://i.imgur.com/OtutZTx.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/204iSUS.jpg"
                        src="https://i.imgur.com/204iSUS.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/ufeRds9.jpg"
                        src="https://i.imgur.com/ufeRds9.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/A2YGlne.jpg"
                        src="https://i.imgur.com/A2YGlne.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/my6Hv4V.jpg"
                        src="https://i.imgur.com/my6Hv4V.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/toSTp8V.jpg"
                        src="https://i.imgur.com/toSTp8V.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/KWSDsf0.jpg"
                        src="https://i.imgur.com/KWSDsf0.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/GUeuUYA.jpg"
                        src="https://i.imgur.com/GUeuUYA.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/eR0sWfD.jpg"
                        src="https://i.imgur.com/eR0sWfD.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/BiiOys4.jpg"
                        src="https://i.imgur.com/BiiOys4.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/fPEAUxp.jpg"
                        src="https://i.imgur.com/fPEAUxp.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/qKgnwqU.jpg"
                        src="https://i.imgur.com/qKgnwqU.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/DtlYwwy.jpg"
                        src="https://i.imgur.com/DtlYwwy.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/yPZxvta.jpg"
                        src="https://i.imgur.com/yPZxvta.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/ornluyi.jpg"
                        src="https://i.imgur.com/ornluyi.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/6JIbpxk.jpg"
                        src="https://i.imgur.com/6JIbpxk.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/abPDVYA.jpg"
                        src="https://i.imgur.com/abPDVYA.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/C9qm4UE.jpg"
                        src="https://i.imgur.com/C9qm4UE.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/OIMYFK8.jpg"
                        src="https://i.imgur.com/OIMYFK8.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/lJ3redM.jpg"
                        src="https://i.imgur.com/lJ3redM.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/kW8C7Pp.jpg"
                        src="https://i.imgur.com/kW8C7Pp.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/8WG9jj9.jpg"
                        src="https://i.imgur.com/8WG9jj9.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/pptR66r.jpg"
                        src="https://i.imgur.com/pptR66r.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/xo5LsUq.jpg"
                        src="https://i.imgur.com/xo5LsUq.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/zNwO3fQ.jpg"
                        src="https://i.imgur.com/zNwO3fQ.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/y4m1puh.jpg"
                        src="https://i.imgur.com/y4m1puh.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/RZ2CbjJ.jpg"
                        src="https://i.imgur.com/RZ2CbjJ.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/D76lfOL.jpg"
                        src="https://i.imgur.com/D76lfOL.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/dOAIcLq.jpg"
                        src="https://i.imgur.com/dOAIcLq.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/3Gd7Dap.jpg"
                        src="https://i.imgur.com/3Gd7Dap.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/0Fd1W36.jpg"
                        src="https://i.imgur.com/0Fd1W36.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/mhekRsJ.jpg"
                        src="https://i.imgur.com/mhekRsJ.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/8H8jnsC.jpg"
                        src="https://i.imgur.com/8H8jnsC.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/qYxi7hE.jpg"
                        src="https://i.imgur.com/qYxi7hE.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/6T5xhDR.jpg"
                        src="https://i.imgur.com/6T5xhDR.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/mc4PH8u.jpg"
                        src="https://i.imgur.com/mc4PH8u.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/NpYpxiN.jpg"
                        src="https://i.imgur.com/NpYpxiN.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/RXkgFmQ.jpg"
                        src="https://i.imgur.com/RXkgFmQ.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/roQCR0E.jpg"
                        src="https://i.imgur.com/roQCR0E.jpg"
                        alt=""
                    />

                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/FBtnkKY.jpg"
                        src="https://i.imgur.com/FBtnkKY.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/O6mxk2H.jpg"
                        src="https://i.imgur.com/O6mxk2H.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/aJJk4RU.jpg"
                        src="https://i.imgur.com/aJJk4RU.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/6PO9jlD.jpg"
                        src="https://i.imgur.com/6PO9jlD.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/CWwgyKM.jpg"
                        src="https://i.imgur.com/CWwgyKM.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/SmkmqrQ.jpg"
                        src="https://i.imgur.com/SmkmqrQ.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/vjZPS7h.jpg"
                        src="https://i.imgur.com/vjZPS7h.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/aZMhZNi.jpg"
                        src="https://i.imgur.com/aZMhZNi.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/cpajapM.jpg"
                        src="https://i.imgur.com/cpajapM.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/2d2QOmz.jpg"
                        src="https://i.imgur.com/2d2QOmz.jpg"
                        alt=""
                    />

                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/HAofKIo.jpg"
                        src="https://i.imgur.com/HAofKIo.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/upRmr7N.jpg"
                        src="https://i.imgur.com/upRmr7N.jpg"
                        alt=""
                    />

                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/RlgZZPe.jpg"
                        src="https://i.imgur.com/RlgZZPe.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/BiljT6j.jpg"
                        src="https://i.imgur.com/BiljT6j.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/XYsM6oI.jpg"
                        src="https://i.imgur.com/XYsM6oI.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/Uola3wM.jpg"
                        src="https://i.imgur.com/Uola3wM.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/GqL1O4T.jpg"
                        src="https://i.imgur.com/GqL1O4T.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/kzkvcBL.jpg"
                        src="https://i.imgur.com/kzkvcBL.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/IUwJ0nB.jpg"
                        src="https://i.imgur.com/IUwJ0nB.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/3wvTd0M.jpg"
                        src="https://i.imgur.com/3wvTd0M.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/3iCg5tC.jpg"
                        src="https://i.imgur.com/3iCg5tC.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/dKEFhwD.jpg"
                        src="https://i.imgur.com/dKEFhwD.jpg"
                        alt=""
                    />
                    <img
                        className="Images-Portfolio"
                        zoomedSrc="https://i.imgur.com/SZFCks3.jpg"
                        src="https://i.imgur.com/SZFCks3.jpg"
                        alt=""
                    />



                </BigPictureGallery>
            </div>



        </div>
    );

}

export default PortfolioImages;